[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "归档"
  url = "/archives/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/yanbin-qiu-ba694450/"
[[main]]
  parent = "Links"
  name = "X"
  url = "https://x.com/"

[[main]]
    name = "留言"
    url = "guestbook/"
    weight = -107

[[main]]
  name = "关于"
  url = "about/"
  weight = -106

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/yabqiu"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://x.com/YanbinQiu"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/yanbin-qiu-ba694450/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"